server:
  port: 8082
spring:
  h2:
    console:
      enabled: true
      path: /credit-service/h2-console
  datasource:
    url: jdbc:h2:tcp://localhost/~/credit-service
    username: ENC(EnIwTwTTxBe6vwtB/5BwvA==)
    password: ENC(100W5Fx6Z9kOfawtHScrBg==)
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true


