server:
  port: 8082
spring:
  sql:
    init:
      mode: always
      data-locations: classpath:schema.sql

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:credit-service
    username: ENC(EnIwTwTTxBe6vwtB/5BwvA==)
    password: #ENC(100W5Fx6Z9kOfawtHScrBg==)
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true


