spring:
  h2:
    console:
      enabled: true
      path: /credit-service/h2-console
  datasource:
    url: jdbc:h2:tcp://localhost/~/credit-service
    username: sa
    password: 123
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true


